### ISSUE TITLE
Problem with t function

### ISSUE THREAD

**Issue by lunac** [web-chefs/DB-LoJack#5]
```
public function logQueries($queries, $connection = null)
    {
        Log::debug(t('Query Count #:count for :url', [  _//This one_ 
            ':count' => count($queries),
            ':url'   => $this->logLabel(),
        ]));
        if (empty($queries)) {
            return;
        }
        $this->makeLogger($this->makeQueryStore($queries, $connection))->writeLogs();
    }

```

I have problem running it, since it says that t function is not defined. I thought maybe you know this issue already. 

```
> @php artisan package:discover

In DBLoJack.php line 151:

  Call to undefined function WebChefs\DBLoJack\t()
```

**Comment by JFossey** [comment]
Thanks, this is a problem, the systems we use this in have the helper t() function and DB-LogJack should not depend on it, so no we did not know about this problem.

I will look to see if I can find time to fix this over the next few days along with another issue we looking into.

**Comment by JFossey** [comment]
@RemoFiorentino please test latest version 1.1
See 0b7340b69997bb7cac4fa19ec1897b0038363ca5 for details
